#pragma once
#include "renderer/gpu_types.h"

namespace phosphor {
// Stable argument table ABI for every F10 entry point. A function declares
// only the slots it consumes. RT AS is slot 0 and its OWN PSO's IFT is slot 4.
PHOSPHOR_GPU_CONSTANT u32 SB_AS = 0u;
PHOSPHOR_GPU_CONSTANT u32 SB_PARAMS = 1u;
PHOSPHOR_GPU_CONSTANT u32 SB_SURFACE = 2u;
PHOSPHOR_GPU_CONSTANT u32 SB_INSTANCES = 3u;
PHOSPHOR_GPU_CONSTANT u32 SB_IFT = 4u;
PHOSPHOR_GPU_CONSTANT u32 SB_MESHES = 5u;
PHOSPHOR_GPU_CONSTANT u32 SB_VERTICES = 6u;
PHOSPHOR_GPU_CONSTANT u32 SB_MESHLETS = 7u;
PHOSPHOR_GPU_CONSTANT u32 SB_MESHLET_VERTICES = 8u;
PHOSPHOR_GPU_CONSTANT u32 SB_MESHLET_TRIANGLES = 9u;
PHOSPHOR_GPU_CONSTANT u32 SB_CANDIDATES_A = 10u;
PHOSPHOR_GPU_CONSTANT u32 SB_CANDIDATES_B = 11u;
PHOSPHOR_GPU_CONSTANT u32 SB_HISTORY_READ = 12u;
PHOSPHOR_GPU_CONSTANT u32 SB_HISTORY_WRITE = 13u;
PHOSPHOR_GPU_CONSTANT u32 SB_CASTER_FLAGS = 14u;
PHOSPHOR_GPU_CONSTANT u32 SB_COUNTERS = 15u;
PHOSPHOR_GPU_CONSTANT u32 SB_MATERIALS = 16u;
PHOSPHOR_GPU_CONSTANT u32 SB_TEXTURES = 17u;
PHOSPHOR_GPU_CONSTANT u32 ST_DEPTH = 0u;
PHOSPHOR_GPU_CONSTANT u32 ST_VISIBILITY = 1u;
PHOSPHOR_GPU_CONSTANT u32 ST_CSM = 2u; // depth2d_array, four reverse-Z layers
PHOSPHOR_GPU_CONSTANT u32 ST_MASK_READ = 3u;
PHOSPHOR_GPU_CONSTANT u32 ST_MASK_WRITE = 4u;
PHOSPHOR_GPU_CONSTANT u32 ST_WORLD_POSITION = 5u; // RGBA32Float, w=guide validity
PHOSPHOR_GPU_CONSTANT u32 ST_GEOMETRIC_NORMAL = 6u; // RGBA16Float, w=guide validity
} // namespace phosphor
